// models/dados.js

const cadastro = [
    {
      id: 1,
      nome: "João Silva",
      email: "joao.silva@email.com",
      telefone: "(11) 98765-4321",
      endereco: "Rua das Flores, 123",
      dataNascimento: "15/05/1990",
      categoria: "Cliente",
      ativo: true,
    },
    {
      id: 2,
      nome: "Maria Oliveira",
      email: "maria.oliveira@email.com",
      telefone: "(21) 91234-5678",
      endereco: "Avenida Principal, 456",
      dataNascimento: "22/11/1985",
      categoria: "Fornecedor",
      ativo: false,
    },
    {
      id: 3,
      nome: "Pedro Souza",
      email: "pedro.souza@email.com",
      telefone: "(31) 95555-1111",
      endereco: "Praça da Paz, 789",
      dataNascimento: "03/08/1992",
      categoria: "Colaborador",
      ativo: true,
    },
    {
      id: 4,
      nome: "Ana Santos",
      email: "ana.santos@email.com",
      telefone: "(41) 97777-2222",
      endereco: "Alameda das Acácias, 10",
      dataNascimento: "10/02/1978",
      categoria: "Cliente",
      ativo: true,
    },
    {
      id: 5,
      nome: "Carlos Ferreira",
      email: "carlos.ferreira@email.com",
      telefone: "(51) 99999-3333",
      endereco: "Rua dos Pinheiros, 200",
      dataNascimento: "25/07/1995",
      categoria: "Fornecedor",
      ativo: true,
    },
    {
      id: 6,
      nome: "Juliana Lima",
      email: "juliana.lima@email.com",
      telefone: "(61) 96666-4444",
      endereco: "Setor Comercial Sul, 50",
      dataNascimento: "30/01/1988",
      categoria: "Cliente",
      ativo: false,
    },
    {
      id: 7,
      nome: "Fernando Costa",
      email: "fernando.costa@email.com",
      telefone: "(71) 94444-5555",
      endereco: "Rua do Sol Nascente, 30",
      dataNascimento: "12/04/1980",
      categoria: "Colaborador",
      ativo: true,
    },
    {
      id: 8,
      nome: "Camila Pereira",
      email: "camila.pereira@email.com",
      telefone: "(81) 92222-6666",
      endereco: "Avenida Boa Viagem, 100",
      dataNascimento: "18/09/1993",
      categoria: "Cliente",
      ativo: true,
    },
    {
      id: 9,
      nome: "Rafael Mendes",
      email: "rafael.mendes@email.com",
      telefone: "(91) 91111-7777",
      endereco: "Travessa da Felicidade, 22",
      dataNascimento: "05/10/1982",
      categoria: "Fornecedor",
      ativo: true,
    },
    {
      id: 10,
      nome: "Patrícia Gomes",
      email: "patricia.gomes@email.com",
      telefone: "(00) 90000-8888",
      endereco: "Rua da Amizade, 99",
      dataNascimento: "09/03/1997",
      categoria: "Colaborador",
      ativo: false,
    },
  ];

  export default {cadastro}